/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: messenger.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "messenger.pb-c.h"
void   alive_status__init
                     (AliveStatus         *message)
{
  static const AliveStatus init_value = ALIVE_STATUS__INIT;
  *message = init_value;
}
size_t alive_status__get_packed_size
                     (const AliveStatus *message)
{
  assert(message->base.descriptor == &alive_status__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t alive_status__pack
                     (const AliveStatus *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &alive_status__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t alive_status__pack_to_buffer
                     (const AliveStatus *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &alive_status__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
AliveStatus *
       alive_status__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (AliveStatus *)
     protobuf_c_message_unpack (&alive_status__descriptor,
                                allocator, len, data);
}
void   alive_status__free_unpacked
                     (AliveStatus *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &alive_status__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
char alive_status__signage__default_value[] = "ESP";
static const ProtobufCFieldDescriptor alive_status__field_descriptors[2] =
{
  {
    "data",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(AliveStatus, data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "signage",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(AliveStatus, signage),
    NULL,
    &alive_status__signage__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned alive_status__field_indices_by_name[] = {
  0,   /* field[0] = data */
  1,   /* field[1] = signage */
};
static const ProtobufCIntRange alive_status__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor alive_status__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "aliveStatus",
  "AliveStatus",
  "AliveStatus",
  "",
  sizeof(AliveStatus),
  2,
  alive_status__field_descriptors,
  alive_status__field_indices_by_name,
  1,  alive_status__number_ranges,
  (ProtobufCMessageInit) alive_status__init,
  NULL,NULL,NULL    /* reserved[123] */
};
