/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: messenger.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "messenger.pb-c.h"
void   frame_header__init
                     (FrameHeader         *message)
{
  static const FrameHeader init_value = FRAME_HEADER__INIT;
  *message = init_value;
}
size_t frame_header__get_packed_size
                     (const FrameHeader *message)
{
  assert(message->base.descriptor == &frame_header__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t frame_header__pack
                     (const FrameHeader *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &frame_header__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t frame_header__pack_to_buffer
                     (const FrameHeader *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &frame_header__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
FrameHeader *
       frame_header__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (FrameHeader *)
     protobuf_c_message_unpack (&frame_header__descriptor,
                                allocator, len, data);
}
void   frame_header__free_unpacked
                     (FrameHeader *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &frame_header__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   test1_data__init
                     (Test1Data         *message)
{
  static const Test1Data init_value = TEST1_DATA__INIT;
  *message = init_value;
}
size_t test1_data__get_packed_size
                     (const Test1Data *message)
{
  assert(message->base.descriptor == &test1_data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t test1_data__pack
                     (const Test1Data *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &test1_data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t test1_data__pack_to_buffer
                     (const Test1Data *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &test1_data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Test1Data *
       test1_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Test1Data *)
     protobuf_c_message_unpack (&test1_data__descriptor,
                                allocator, len, data);
}
void   test1_data__free_unpacked
                     (Test1Data *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &test1_data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   test1_options__init
                     (Test1Options         *message)
{
  static const Test1Options init_value = TEST1_OPTIONS__INIT;
  *message = init_value;
}
size_t test1_options__get_packed_size
                     (const Test1Options *message)
{
  assert(message->base.descriptor == &test1_options__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t test1_options__pack
                     (const Test1Options *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &test1_options__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t test1_options__pack_to_buffer
                     (const Test1Options *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &test1_options__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Test1Options *
       test1_options__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Test1Options *)
     protobuf_c_message_unpack (&test1_options__descriptor,
                                allocator, len, data);
}
void   test1_options__free_unpacked
                     (Test1Options *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &test1_options__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sensor1_data__init
                     (Sensor1Data         *message)
{
  static const Sensor1Data init_value = SENSOR1_DATA__INIT;
  *message = init_value;
}
size_t sensor1_data__get_packed_size
                     (const Sensor1Data *message)
{
  assert(message->base.descriptor == &sensor1_data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sensor1_data__pack
                     (const Sensor1Data *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sensor1_data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sensor1_data__pack_to_buffer
                     (const Sensor1Data *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sensor1_data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Sensor1Data *
       sensor1_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Sensor1Data *)
     protobuf_c_message_unpack (&sensor1_data__descriptor,
                                allocator, len, data);
}
void   sensor1_data__free_unpacked
                     (Sensor1Data *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sensor1_data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sensor1_options__init
                     (Sensor1Options         *message)
{
  static const Sensor1Options init_value = SENSOR1_OPTIONS__INIT;
  *message = init_value;
}
size_t sensor1_options__get_packed_size
                     (const Sensor1Options *message)
{
  assert(message->base.descriptor == &sensor1_options__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sensor1_options__pack
                     (const Sensor1Options *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sensor1_options__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sensor1_options__pack_to_buffer
                     (const Sensor1Options *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sensor1_options__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Sensor1Options *
       sensor1_options__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Sensor1Options *)
     protobuf_c_message_unpack (&sensor1_options__descriptor,
                                allocator, len, data);
}
void   sensor1_options__free_unpacked
                     (Sensor1Options *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sensor1_options__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   frame_payload__init
                     (FramePayload         *message)
{
  static const FramePayload init_value = FRAME_PAYLOAD__INIT;
  *message = init_value;
}
size_t frame_payload__get_packed_size
                     (const FramePayload *message)
{
  assert(message->base.descriptor == &frame_payload__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t frame_payload__pack
                     (const FramePayload *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &frame_payload__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t frame_payload__pack_to_buffer
                     (const FramePayload *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &frame_payload__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
FramePayload *
       frame_payload__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (FramePayload *)
     protobuf_c_message_unpack (&frame_payload__descriptor,
                                allocator, len, data);
}
void   frame_payload__free_unpacked
                     (FramePayload *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &frame_payload__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor frame_header__field_descriptors[2] =
{
  {
    "next_message_size",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FIXED32,
    0,   /* quantifier_offset */
    offsetof(FrameHeader, next_message_size),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "crc",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FIXED32,
    0,   /* quantifier_offset */
    offsetof(FrameHeader, crc),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned frame_header__field_indices_by_name[] = {
  1,   /* field[1] = crc */
  0,   /* field[0] = next_message_size */
};
static const ProtobufCIntRange frame_header__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor frame_header__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "FrameHeader",
  "FrameHeader",
  "FrameHeader",
  "",
  sizeof(FrameHeader),
  2,
  frame_header__field_descriptors,
  frame_header__field_indices_by_name,
  1,  frame_header__number_ranges,
  (ProtobufCMessageInit) frame_header__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor test1_data__field_descriptors[1] =
{
  {
    "test_data",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Test1Data, test_data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned test1_data__field_indices_by_name[] = {
  0,   /* field[0] = test_data */
};
static const ProtobufCIntRange test1_data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor test1_data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Test1Data",
  "Test1Data",
  "Test1Data",
  "",
  sizeof(Test1Data),
  1,
  test1_data__field_descriptors,
  test1_data__field_indices_by_name,
  1,  test1_data__number_ranges,
  (ProtobufCMessageInit) test1_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor test1_options__field_descriptors[1] =
{
  {
    "enable",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Test1Options, enable),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned test1_options__field_indices_by_name[] = {
  0,   /* field[0] = enable */
};
static const ProtobufCIntRange test1_options__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor test1_options__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Test1Options",
  "Test1Options",
  "Test1Options",
  "",
  sizeof(Test1Options),
  1,
  test1_options__field_descriptors,
  test1_options__field_indices_by_name,
  1,  test1_options__number_ranges,
  (ProtobufCMessageInit) test1_options__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sensor1_data__field_descriptors[1] =
{
  {
    "sensor1_data",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Sensor1Data, sensor1_data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sensor1_data__field_indices_by_name[] = {
  0,   /* field[0] = sensor1_data */
};
static const ProtobufCIntRange sensor1_data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor sensor1_data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Sensor1Data",
  "Sensor1Data",
  "Sensor1Data",
  "",
  sizeof(Sensor1Data),
  1,
  sensor1_data__field_descriptors,
  sensor1_data__field_indices_by_name,
  1,  sensor1_data__number_ranges,
  (ProtobufCMessageInit) sensor1_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sensor1_options__field_descriptors[1] =
{
  {
    "enable",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Sensor1Options, enable),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sensor1_options__field_indices_by_name[] = {
  0,   /* field[0] = enable */
};
static const ProtobufCIntRange sensor1_options__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor sensor1_options__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Sensor1Options",
  "Sensor1Options",
  "Sensor1Options",
  "",
  sizeof(Sensor1Options),
  1,
  sensor1_options__field_descriptors,
  sensor1_options__field_indices_by_name,
  1,  sensor1_options__number_ranges,
  (ProtobufCMessageInit) sensor1_options__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor frame_payload__field_descriptors[4] =
{
  {
    "test1_data",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(FramePayload, payload_case),
    offsetof(FramePayload, test1_data),
    &test1_data__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "test1_options",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(FramePayload, payload_case),
    offsetof(FramePayload, test1_options),
    &test1_options__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sensor1_data",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(FramePayload, payload_case),
    offsetof(FramePayload, sensor1_data),
    &sensor1_data__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sensor1_options",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(FramePayload, payload_case),
    offsetof(FramePayload, sensor1_options),
    &sensor1_options__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned frame_payload__field_indices_by_name[] = {
  2,   /* field[2] = sensor1_data */
  3,   /* field[3] = sensor1_options */
  0,   /* field[0] = test1_data */
  1,   /* field[1] = test1_options */
};
static const ProtobufCIntRange frame_payload__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor frame_payload__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "FramePayload",
  "FramePayload",
  "FramePayload",
  "",
  sizeof(FramePayload),
  4,
  frame_payload__field_descriptors,
  frame_payload__field_indices_by_name,
  1,  frame_payload__number_ranges,
  (ProtobufCMessageInit) frame_payload__init,
  NULL,NULL,NULL    /* reserved[123] */
};
