// messenger version 0.1.1
syntax = "proto2";

message FrameHeader {
  required fixed32 next_message_size = 1;
  required fixed32 crc = 2;
}

// Intermediate data structures
message Test1Data {
  required int32 test_data = 1;
}

message Test1Options {
  required bool enable = 1;
}

message Sensor1Data {
  required int32 sensor1_data = 1;
}

message Sensor1Options {
  required bool enable = 1;
}

// The main payload envelope
message FramePayload {
  oneof payload {
    Test1Data test1_data = 1;
    Test1Options test1_options = 2;
    Sensor1Data sensor1_data = 3;
    Sensor1Options sensor1_options = 4;
  }
}