/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_MESSENGER_PB_H_INCLUDED
#define PB_MESSENGER_PB_H_INCLUDED
#include "pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _aliveStatus {
    int32_t data;
    pb_callback_t signage;
} aliveStatus;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define aliveStatus_init_default                 {0, {{NULL}, NULL}}
#define aliveStatus_init_zero                    {0, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define aliveStatus_data_tag                     1
#define aliveStatus_signage_tag                  2

/* Struct field encoding specification for nanopb */
#define aliveStatus_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT32,    data,              1) \
X(a, CALLBACK, REQUIRED, STRING,   signage,           2)
#define aliveStatus_CALLBACK pb_default_field_callback
#define aliveStatus_DEFAULT NULL

extern const pb_msgdesc_t aliveStatus_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define aliveStatus_fields &aliveStatus_msg

/* Maximum encoded size of messages (where known) */
/* aliveStatus_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
