/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "messenger.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(FrameHeader, FrameHeader, AUTO)


PB_BIND(TestIntConfig, TestIntConfig, AUTO)


PB_BIND(TestIntData, TestIntData, AUTO)


PB_BIND(TestBandwidthConfig, TestBandwidthConfig, AUTO)


PB_BIND(TestBandwidthData, TestBandwidthData, 2)


PB_BIND(StreamConfig, StreamConfig, AUTO)


PB_BIND(StreamData, StreamData, 2)


PB_BIND(FramePayload, FramePayload, 4)



