/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "messenger.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(FrameHeader, FrameHeader, AUTO)


PB_BIND(Test1Data, Test1Data, AUTO)


PB_BIND(Test1Options, Test1Options, AUTO)


PB_BIND(Sensor1Data, Sensor1Data, AUTO)


PB_BIND(Sensor1Options, Sensor1Options, AUTO)


PB_BIND(FramePayload, FramePayload, AUTO)



