/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "messenger.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(MessageID, MessageID, AUTO)


PB_BIND(Link1_options, Link1_options, AUTO)


PB_BIND(Link1_data, Link1_data, AUTO)





