/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: messenger.proto */

#ifndef PROTOBUF_C_messenger_2eproto__INCLUDED
#define PROTOBUF_C_messenger_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _FrameHeader FrameHeader;
typedef struct _TestIntConfig TestIntConfig;
typedef struct _TestIntData TestIntData;
typedef struct _TestBandwidthConfig TestBandwidthConfig;
typedef struct _TestBandwidthData TestBandwidthData;
typedef struct _StreamConfig StreamConfig;
typedef struct _StreamData StreamData;
typedef struct _FramePayload FramePayload;


/* --- enums --- */


/* --- messages --- */

struct  _FrameHeader
{
  ProtobufCMessage base;
  uint32_t next_message_size;
  uint32_t crc;
};
#define FRAME_HEADER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&frame_header__descriptor) \
    , 0, 0 }


/*
 * -----------------------------------------
 * Program 1: Test Int
 * -----------------------------------------
 */
struct  _TestIntConfig
{
  ProtobufCMessage base;
  protobuf_c_boolean enable;
};
#define TEST_INT_CONFIG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&test_int_config__descriptor) \
    , 0 }


struct  _TestIntData
{
  ProtobufCMessage base;
  int32_t value;
};
#define TEST_INT_DATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&test_int_data__descriptor) \
    , 0 }


/*
 * -----------------------------------------
 * Program 2: Test Bandwidth
 * -----------------------------------------
 */
struct  _TestBandwidthConfig
{
  ProtobufCMessage base;
  protobuf_c_boolean enable;
  /*
   * Let the receiver know how large the dummy payloads should be
   */
  protobuf_c_boolean has_payload_size;
  uint32_t payload_size;
};
#define TEST_BANDWIDTH_CONFIG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&test_bandwidth_config__descriptor) \
    , 0, 0, 1024u }


struct  _TestBandwidthData
{
  ProtobufCMessage base;
  /*
   * A generic buffer to test throughput
   */
  ProtobufCBinaryData dummy_data;
};
#define TEST_BANDWIDTH_DATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&test_bandwidth_data__descriptor) \
    , {0,NULL} }


/*
 * -----------------------------------------
 * Program 3: Streaming (DAC/ADC)
 * -----------------------------------------
 */
struct  _StreamConfig
{
  ProtobufCMessage base;
  protobuf_c_boolean enable;
  protobuf_c_boolean has_sample_rate_hz;
  uint32_t sample_rate_hz;
  /*
   * Tell the ESP32 how many samples to bundle per frame (e.g., 100)
   */
  protobuf_c_boolean has_samples_per_frame;
  uint32_t samples_per_frame;
};
#define STREAM_CONFIG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&stream_config__descriptor) \
    , 0, 0, 1000u, 0, 100u }


struct  _StreamData
{
  ProtobufCMessage base;
  /*
   * 'repeated' fields are inherently optional. 
   * If you only populate dac_values, adc_values takes up 0 bytes over UART.
   */
  size_t n_adc_values;
  int32_t *adc_values;
  size_t n_dac_values;
  int32_t *dac_values;
};
#define STREAM_DATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&stream_data__descriptor) \
    , 0,NULL, 0,NULL }


typedef enum {
  FRAME_PAYLOAD__PAYLOAD__NOT_SET = 0,
  FRAME_PAYLOAD__PAYLOAD_TEST_INT_CONFIG = 1,
  FRAME_PAYLOAD__PAYLOAD_TEST_INT_DATA = 2,
  FRAME_PAYLOAD__PAYLOAD_TEST_BANDWIDTH_CONFIG = 3,
  FRAME_PAYLOAD__PAYLOAD_TEST_BANDWIDTH_DATA = 4,
  FRAME_PAYLOAD__PAYLOAD_STREAM_CONFIG = 5,
  FRAME_PAYLOAD__PAYLOAD_STREAM_DATA = 6
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(FRAME_PAYLOAD__PAYLOAD)
} FramePayload__PayloadCase;

/*
 * -----------------------------------------
 * Main Envelope
 * -----------------------------------------
 */
struct  _FramePayload
{
  ProtobufCMessage base;
  FramePayload__PayloadCase payload_case;
  union {
    /*
     * 1. Test Int
     */
    TestIntConfig *test_int_config;
    TestIntData *test_int_data;
    /*
     * 2. Test Bandwidth
     */
    TestBandwidthConfig *test_bandwidth_config;
    TestBandwidthData *test_bandwidth_data;
    /*
     * 3. Streaming
     */
    StreamConfig *stream_config;
    StreamData *stream_data;
  };
};
#define FRAME_PAYLOAD__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&frame_payload__descriptor) \
    , FRAME_PAYLOAD__PAYLOAD__NOT_SET, {0} }


/* FrameHeader methods */
void   frame_header__init
                     (FrameHeader         *message);
size_t frame_header__get_packed_size
                     (const FrameHeader   *message);
size_t frame_header__pack
                     (const FrameHeader   *message,
                      uint8_t             *out);
size_t frame_header__pack_to_buffer
                     (const FrameHeader   *message,
                      ProtobufCBuffer     *buffer);
FrameHeader *
       frame_header__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   frame_header__free_unpacked
                     (FrameHeader *message,
                      ProtobufCAllocator *allocator);
/* TestIntConfig methods */
void   test_int_config__init
                     (TestIntConfig         *message);
size_t test_int_config__get_packed_size
                     (const TestIntConfig   *message);
size_t test_int_config__pack
                     (const TestIntConfig   *message,
                      uint8_t             *out);
size_t test_int_config__pack_to_buffer
                     (const TestIntConfig   *message,
                      ProtobufCBuffer     *buffer);
TestIntConfig *
       test_int_config__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   test_int_config__free_unpacked
                     (TestIntConfig *message,
                      ProtobufCAllocator *allocator);
/* TestIntData methods */
void   test_int_data__init
                     (TestIntData         *message);
size_t test_int_data__get_packed_size
                     (const TestIntData   *message);
size_t test_int_data__pack
                     (const TestIntData   *message,
                      uint8_t             *out);
size_t test_int_data__pack_to_buffer
                     (const TestIntData   *message,
                      ProtobufCBuffer     *buffer);
TestIntData *
       test_int_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   test_int_data__free_unpacked
                     (TestIntData *message,
                      ProtobufCAllocator *allocator);
/* TestBandwidthConfig methods */
void   test_bandwidth_config__init
                     (TestBandwidthConfig         *message);
size_t test_bandwidth_config__get_packed_size
                     (const TestBandwidthConfig   *message);
size_t test_bandwidth_config__pack
                     (const TestBandwidthConfig   *message,
                      uint8_t             *out);
size_t test_bandwidth_config__pack_to_buffer
                     (const TestBandwidthConfig   *message,
                      ProtobufCBuffer     *buffer);
TestBandwidthConfig *
       test_bandwidth_config__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   test_bandwidth_config__free_unpacked
                     (TestBandwidthConfig *message,
                      ProtobufCAllocator *allocator);
/* TestBandwidthData methods */
void   test_bandwidth_data__init
                     (TestBandwidthData         *message);
size_t test_bandwidth_data__get_packed_size
                     (const TestBandwidthData   *message);
size_t test_bandwidth_data__pack
                     (const TestBandwidthData   *message,
                      uint8_t             *out);
size_t test_bandwidth_data__pack_to_buffer
                     (const TestBandwidthData   *message,
                      ProtobufCBuffer     *buffer);
TestBandwidthData *
       test_bandwidth_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   test_bandwidth_data__free_unpacked
                     (TestBandwidthData *message,
                      ProtobufCAllocator *allocator);
/* StreamConfig methods */
void   stream_config__init
                     (StreamConfig         *message);
size_t stream_config__get_packed_size
                     (const StreamConfig   *message);
size_t stream_config__pack
                     (const StreamConfig   *message,
                      uint8_t             *out);
size_t stream_config__pack_to_buffer
                     (const StreamConfig   *message,
                      ProtobufCBuffer     *buffer);
StreamConfig *
       stream_config__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   stream_config__free_unpacked
                     (StreamConfig *message,
                      ProtobufCAllocator *allocator);
/* StreamData methods */
void   stream_data__init
                     (StreamData         *message);
size_t stream_data__get_packed_size
                     (const StreamData   *message);
size_t stream_data__pack
                     (const StreamData   *message,
                      uint8_t             *out);
size_t stream_data__pack_to_buffer
                     (const StreamData   *message,
                      ProtobufCBuffer     *buffer);
StreamData *
       stream_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   stream_data__free_unpacked
                     (StreamData *message,
                      ProtobufCAllocator *allocator);
/* FramePayload methods */
void   frame_payload__init
                     (FramePayload         *message);
size_t frame_payload__get_packed_size
                     (const FramePayload   *message);
size_t frame_payload__pack
                     (const FramePayload   *message,
                      uint8_t             *out);
size_t frame_payload__pack_to_buffer
                     (const FramePayload   *message,
                      ProtobufCBuffer     *buffer);
FramePayload *
       frame_payload__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   frame_payload__free_unpacked
                     (FramePayload *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*FrameHeader_Closure)
                 (const FrameHeader *message,
                  void *closure_data);
typedef void (*TestIntConfig_Closure)
                 (const TestIntConfig *message,
                  void *closure_data);
typedef void (*TestIntData_Closure)
                 (const TestIntData *message,
                  void *closure_data);
typedef void (*TestBandwidthConfig_Closure)
                 (const TestBandwidthConfig *message,
                  void *closure_data);
typedef void (*TestBandwidthData_Closure)
                 (const TestBandwidthData *message,
                  void *closure_data);
typedef void (*StreamConfig_Closure)
                 (const StreamConfig *message,
                  void *closure_data);
typedef void (*StreamData_Closure)
                 (const StreamData *message,
                  void *closure_data);
typedef void (*FramePayload_Closure)
                 (const FramePayload *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor frame_header__descriptor;
extern const ProtobufCMessageDescriptor test_int_config__descriptor;
extern const ProtobufCMessageDescriptor test_int_data__descriptor;
extern const ProtobufCMessageDescriptor test_bandwidth_config__descriptor;
extern const ProtobufCMessageDescriptor test_bandwidth_data__descriptor;
extern const ProtobufCMessageDescriptor stream_config__descriptor;
extern const ProtobufCMessageDescriptor stream_data__descriptor;
extern const ProtobufCMessageDescriptor frame_payload__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_messenger_2eproto__INCLUDED */
