/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: messenger.proto */

#ifndef PROTOBUF_C_messenger_2eproto__INCLUDED
#define PROTOBUF_C_messenger_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _FrameHeader FrameHeader;
typedef struct _Test1Data Test1Data;
typedef struct _Test1Options Test1Options;
typedef struct _Sensor1Data Sensor1Data;
typedef struct _Sensor1Options Sensor1Options;
typedef struct _FramePayload FramePayload;


/* --- enums --- */


/* --- messages --- */

struct  _FrameHeader
{
  ProtobufCMessage base;
  uint32_t next_message_size;
  uint32_t crc;
};
#define FRAME_HEADER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&frame_header__descriptor) \
    , 0, 0 }


/*
 * Intermediate data structures
 */
struct  _Test1Data
{
  ProtobufCMessage base;
  int32_t test_data;
};
#define TEST1_DATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&test1_data__descriptor) \
    , 0 }


struct  _Test1Options
{
  ProtobufCMessage base;
  protobuf_c_boolean enable;
};
#define TEST1_OPTIONS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&test1_options__descriptor) \
    , 0 }


struct  _Sensor1Data
{
  ProtobufCMessage base;
  int32_t sensor1_data;
};
#define SENSOR1_DATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&sensor1_data__descriptor) \
    , 0 }


struct  _Sensor1Options
{
  ProtobufCMessage base;
  protobuf_c_boolean enable;
};
#define SENSOR1_OPTIONS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&sensor1_options__descriptor) \
    , 0 }


typedef enum {
  FRAME_PAYLOAD__PAYLOAD__NOT_SET = 0,
  FRAME_PAYLOAD__PAYLOAD_TEST1_DATA = 1,
  FRAME_PAYLOAD__PAYLOAD_TEST1_OPTIONS = 2,
  FRAME_PAYLOAD__PAYLOAD_SENSOR1_DATA = 3,
  FRAME_PAYLOAD__PAYLOAD_SENSOR1_OPTIONS = 4
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(FRAME_PAYLOAD__PAYLOAD)
} FramePayload__PayloadCase;

/*
 * The main payload envelope
 */
struct  _FramePayload
{
  ProtobufCMessage base;
  FramePayload__PayloadCase payload_case;
  union {
    Test1Data *test1_data;
    Test1Options *test1_options;
    Sensor1Data *sensor1_data;
    Sensor1Options *sensor1_options;
  };
};
#define FRAME_PAYLOAD__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&frame_payload__descriptor) \
    , FRAME_PAYLOAD__PAYLOAD__NOT_SET, {0} }


/* FrameHeader methods */
void   frame_header__init
                     (FrameHeader         *message);
size_t frame_header__get_packed_size
                     (const FrameHeader   *message);
size_t frame_header__pack
                     (const FrameHeader   *message,
                      uint8_t             *out);
size_t frame_header__pack_to_buffer
                     (const FrameHeader   *message,
                      ProtobufCBuffer     *buffer);
FrameHeader *
       frame_header__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   frame_header__free_unpacked
                     (FrameHeader *message,
                      ProtobufCAllocator *allocator);
/* Test1Data methods */
void   test1_data__init
                     (Test1Data         *message);
size_t test1_data__get_packed_size
                     (const Test1Data   *message);
size_t test1_data__pack
                     (const Test1Data   *message,
                      uint8_t             *out);
size_t test1_data__pack_to_buffer
                     (const Test1Data   *message,
                      ProtobufCBuffer     *buffer);
Test1Data *
       test1_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   test1_data__free_unpacked
                     (Test1Data *message,
                      ProtobufCAllocator *allocator);
/* Test1Options methods */
void   test1_options__init
                     (Test1Options         *message);
size_t test1_options__get_packed_size
                     (const Test1Options   *message);
size_t test1_options__pack
                     (const Test1Options   *message,
                      uint8_t             *out);
size_t test1_options__pack_to_buffer
                     (const Test1Options   *message,
                      ProtobufCBuffer     *buffer);
Test1Options *
       test1_options__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   test1_options__free_unpacked
                     (Test1Options *message,
                      ProtobufCAllocator *allocator);
/* Sensor1Data methods */
void   sensor1_data__init
                     (Sensor1Data         *message);
size_t sensor1_data__get_packed_size
                     (const Sensor1Data   *message);
size_t sensor1_data__pack
                     (const Sensor1Data   *message,
                      uint8_t             *out);
size_t sensor1_data__pack_to_buffer
                     (const Sensor1Data   *message,
                      ProtobufCBuffer     *buffer);
Sensor1Data *
       sensor1_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   sensor1_data__free_unpacked
                     (Sensor1Data *message,
                      ProtobufCAllocator *allocator);
/* Sensor1Options methods */
void   sensor1_options__init
                     (Sensor1Options         *message);
size_t sensor1_options__get_packed_size
                     (const Sensor1Options   *message);
size_t sensor1_options__pack
                     (const Sensor1Options   *message,
                      uint8_t             *out);
size_t sensor1_options__pack_to_buffer
                     (const Sensor1Options   *message,
                      ProtobufCBuffer     *buffer);
Sensor1Options *
       sensor1_options__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   sensor1_options__free_unpacked
                     (Sensor1Options *message,
                      ProtobufCAllocator *allocator);
/* FramePayload methods */
void   frame_payload__init
                     (FramePayload         *message);
size_t frame_payload__get_packed_size
                     (const FramePayload   *message);
size_t frame_payload__pack
                     (const FramePayload   *message,
                      uint8_t             *out);
size_t frame_payload__pack_to_buffer
                     (const FramePayload   *message,
                      ProtobufCBuffer     *buffer);
FramePayload *
       frame_payload__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   frame_payload__free_unpacked
                     (FramePayload *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*FrameHeader_Closure)
                 (const FrameHeader *message,
                  void *closure_data);
typedef void (*Test1Data_Closure)
                 (const Test1Data *message,
                  void *closure_data);
typedef void (*Test1Options_Closure)
                 (const Test1Options *message,
                  void *closure_data);
typedef void (*Sensor1Data_Closure)
                 (const Sensor1Data *message,
                  void *closure_data);
typedef void (*Sensor1Options_Closure)
                 (const Sensor1Options *message,
                  void *closure_data);
typedef void (*FramePayload_Closure)
                 (const FramePayload *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor frame_header__descriptor;
extern const ProtobufCMessageDescriptor test1_data__descriptor;
extern const ProtobufCMessageDescriptor test1_options__descriptor;
extern const ProtobufCMessageDescriptor sensor1_data__descriptor;
extern const ProtobufCMessageDescriptor sensor1_options__descriptor;
extern const ProtobufCMessageDescriptor frame_payload__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_messenger_2eproto__INCLUDED */
